swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
  
paths:
  /transactions:
    post:
      summary: Creates a new transaction.
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: OK 
          schema: 
            $ref: '#/definitions/Transaction'
  /limits:
    post:
      summary: Creates a new limit.
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Limit'
      responses:
        200:
          description: OK 
          schema: 
            $ref: '#/definitions/LimitGet'
  /limits/{client_id}:
    get:
      summary: Returns a limit by client_id.
      parameters:
        - in: path
          name: client_id
          required: true
          type: integer
          minimum: 1
          description: The ID of the limit to return.
      responses:
        200:
          description: A User object.
          schema:
            $ref: '#/definitions/LimitGet'
        400:
          description: The specified limit ID is invalid (e.g. not a number).
        404:
          description: A limit with the specified ID was not found.
        default:
          description: Unexpected error
    delete:
      summary: Delets a limit by client_id.
      parameters:
        - in: path
          name: client_id
          required: true
          type: integer
          minimum: 1
          description: The ID of the limit to return.
      responses:
        200:
          description: Deleted.
        400:
          description: The specified limit ID is invalid (e.g. not a number).
        404:
          description: A limit with the specified ID was not found.
        default:
          description: Unexpected error
    put:
      summary: Updates a limit by ID.
      parameters:
        - in: path
          name: client_id
          required: true
          type: integer
        - in: "body"
          name: "body"
          description: "Updated user object"
          required: true
          schema:
            $ref: "#/definitions/Limit"

      responses:
        200:
          description: Updated.
          schema:
            $ref : '#/definitions/LimitGet'
        400:
          description: The specified limit ID is invalid (e.g. not a number).
        404:
          description: A limit with the specified ID was not found.
        default:
          description: Unexpected error   

definitions:
  Transaction:
    properties:
      client_id:
        type : integer
      country:
        type: string
        enum : ["RUS","ABH","AUS"]
      cur:
        type : string
        enum : ["RUB","USD","EUR"]
      amount: 
        type : integer
      date: 
        type : integer
      
  Limit:
    properties:
      country:
        type: string
        enum : ["RUS","ABH","AUS"]
      cur:
        type : string
        enum : ["RUB","USD","EUR"]
      limit:
        type : integer
  LimitGet:
    properties:
      client_id:
        type: integer
      country:
        type: string
        enum : ["RUS","ABH","AUS"]
      cur:
        type : string
        enum : ["RUB","USD","EUR"]
      limit:
        type : integer
